### ISSUE TITLE
Do not create folders in the main /home/user folder

### ISSUE THREAD

**Issue by donadigo** [SuburbanFilth/Noted#8]
The application should not create any folders inside the `/home/user` folder. The app should create a data folder in `/home/user/.local/share`, which you can get by callling `glib.get_user_data_dir()`.

**Comment by marsp0** [comment]
Hey @donadigo ,

I assume you are the person reviewing the submission for the AppCenter. I will patch it tonight or tomorrow. Should i create a new release when I'm done ?

**Comment by donadigo** [comment]
Yes, I'm the one who dismissed it. After you've patched that, make a new release, yes.

**Comment by marsp0** [comment]
Alright, thank you!

**Comment by marsp0** [comment]
Fixed with https://github.com/SuburbanFilth/Noted/commit/4bf1d26c84cfb633d667c478252ac9f8e24255aa
