### ISSUE TITLE
Screenshot is too aggressively cropped

### ISSUE THREAD

**Issue by danirabbit** [SuburbanFilth/Noted#9]
You should use the built in screenshot tool with the mode "Grab current window" to get a transparent screenshot, including the window shadow.

**Comment by marsp0** [comment]
@danrabbit I actually had a problem with that. When I try to take the screenshot with Grab the current window option I do not see anything in the file. Below you can see it is completely white. Do you know how to fix that ?
![screenshot from 2017-09-08 22 27 18](https://user-images.githubusercontent.com/7538637/30228186-4bec0c94-94e5-11e7-8514-057fa0728880.png)

**Comment by danirabbit** [comment]
Hm I can't reproduce that here. Here's a screenshot I just took: 
![screenshot from 2017-09-08 14 15 12](https://user-images.githubusercontent.com/7277719/30231519-30520d98-94a0-11e7-86df-1a486324e287.png)

**Comment by marsp0** [comment]
Awesome, will include this one in the file.

**Comment by btkostner** [comment]
Do you happen to have an nvidia GPU? It sounds very similar to a bunch of nvidia driver issues I have.

**Comment by marsp0** [comment]
yeah, 1060 with driver version 375.66
